events {
  worker_connections 1024;
}

http {
  client_max_body_size 200M;

  upstream api_upstream {
    server api:8000;
  }

  upstream frontend_upstream {
    server frontend:3000;
  }

  server {
    listen 80;

    location /api/ {
      rewrite ^/api/(.*)$ /$1 break;
      proxy_pass http://api_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
      proxy_pass http://frontend_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
